/home/ubuntu/ocean_annotations_platform/backups/push_backup.sh: line 4: python: command not found
